update atomiccomponents docs
nextcloud/documentation pull request #10399
Opened 2023-05-16 16:59 UTC by szaimen

Fix part of https://github.com/nextcloud/documentation/issues/10392

TODO:
- [ ] Update all screenshots
- [ ] add links to components (vue and penpot)?
- [ ] add missing components?

2023-05-16 17:00 UTC, szaimen commented on developer_manual/images/button-primary-secondary.png
Maybe the text should not be in there?

2023-05-17 16:26 UTC, szaimen commented on developer_manual/images/action-menu-new-item.gif
Should this stay a gif?

2023-05-17 16:26 UTC, szaimen commented on developer_manual/images/action-menu-second-level.gif
should this stay a gif?

2023-05-17 16:27 UTC, szaimen commented on developer_manual/images/avatar-talk.gif
I guess I will need a better test account here in order to create a better screenshot. This is only a placeholder for now

2023-05-17 16:27 UTC, szaimen commented on developer_manual/images/colour-picker.gif
should this stay a gif?

2023-05-17 16:27 UTC, szaimen commented on developer_manual/images/dropdown-find-as-you-type.gif
should this stay a gif?

2023-05-24 15:10 UTC, szaimen commented on developer_manual/images/skeleton-screen-talk.png
I am not sure honestly. Should probably be reported to the talk team? cc @marcoambrosini 😉

2023-05-24 15:13 UTC, jancborchardt commented on developer_manual/images/meter-settings.png
- There is no discernible contrast here between the filled part of the bar and the rest – and it looks different from https://nextcloud-vue-components.netlify.app/#/Components/NcProgressBar ?
- It’s also barely filled, better would be an example like before with it partly filled

2023-05-24 15:15 UTC, jancborchardt commented on developer_manual/images/dropdown-find-as-you-type.gif
Doesn’t need to be an animated GIF I think. And if it’s not animated it should be a png so they grey doesn’t look so dithered. :D

2023-05-24 15:20 UTC, szaimen commented on developer_manual/images/meter-settings.png
This is how it currently looks... in the files app. but I agree the example could be better with half-filled or something quota...

2023-05-24 15:21 UTC, jancborchardt commented on developer_manual/images/colour-picker.gif
Doesn’t need to stay a gif either. 2 other things which are off:
- The border-radius of this menu is smaller than the one of the action menu
- The menu touches the left viewport edge – it should have some clearance, like at least 4px?

2023-05-24 15:22 UTC, jancborchardt commented on developer_manual/images/button-primary-secondary.png
Yeah, we shouldn’t have text in screenshots but in actual text. And the actual example as before was good, with Copy secondary and Move primary, as that is how it appears in the actual "Move or copy" dialog.

2023-05-24 15:23 UTC, jancborchardt commented on developer_manual/images/avatar-talk.gif
Yup! Also, the status icon seems to be broken? Very large white bar in the "do not disturb" icon.

2023-05-24 15:24 UTC, jancborchardt commented on developer_manual/images/action-menu-second-level.gif
I would say here it makes sense, since we should communicate how the second level is reachable and how to go back.

2023-05-24 15:24 UTC, jancborchardt commented on developer_manual/images/colour-picker.gif
Actually should also be a gif since it has 2 levels, sorry!

2023-05-24 15:31 UTC, jancborchardt commented on developer_manual/images/action-menu-new-item.gif
Yes I’d say a gif gives proper context. Also, regarding the component – the submit / arrow button is missing in the new one.

2023-05-24 15:32 UTC, jancborchardt commented on developer_manual/images/action-menu-icon.png
The screenshot looks blurry?

2023-05-24 15:33 UTC, jancborchardt requested changes
See inline comments. :)

2023-06-01 14:03 UTC, szaimen commented on developer_manual/images/action-menu-icon.png
should be fixed now

2023-06-01 14:04 UTC, szaimen commented on developer_manual/images/action-menu-radio-button.gif
fixed

2023-06-01 14:04 UTC, szaimen commented on developer_manual/images/avatar-talk.gif
fixed

2023-06-01 14:04 UTC, szaimen commented on developer_manual/images/button-primary-secondary.png
fixed

2023-06-01 14:04 UTC, szaimen commented on developer_manual/images/colour-picker.gif
fixed

2023-06-01 14:05 UTC, szaimen commented on developer_manual/images/dropdown-find-as-you-type.gif
fixed

2023-06-01 14:05 UTC, szaimen commented on developer_manual/images/talk-counter-bubble.png
should be fixed now

2023-06-01 15:26 UTC, jancborchardt commented on developer_manual/images/skeleton-screen-talk.png
Could we then use a different gif? It's not an ideal example, we don't want people to do it like that. :D

2023-06-01 22:41 UTC, szaimen commented on developer_manual/images/skeleton-screen-talk.png
also fixed now

2023-06-07 10:09 UTC, szaimen commented on developer_manual/images/action-menu-new-item.gif
component needs update (arrow always visible, input filed jumps

2023-06-07 10:10 UTC, szaimen commented on developer_manual/images/action-menu-radio-button.gif
button getting disabled for a split second looks strange

2023-06-07 10:21 UTC, szaimen commented on developer_manual/images/colour-picker.gif
need new border-radius

2023-06-07 10:24 UTC, szaimen commented on developer_manual/images/deck-card-modal.png
remove red underline

2023-06-07 10:25 UTC, szaimen commented on developer_manual/images/dropdown-find-as-you-type.gif
why does it close as you type?

2023-06-07 10:26 UTC, szaimen commented on developer_manual/images/skeleton-screen-talk.png
check where to adjust initial loading color

2023-06-07 10:30 UTC, szaimen commented on developer_manual/images/talk-counter-bubble.png
aligning is off

2023-06-08 13:32 UTC, szaimen commented on developer_manual/images/action-menu-radio-button.gif
reported to https://github.com/nextcloud/server/issues/38711

2023-06-08 13:40 UTC, szaimen commented on developer_manual/images/avatar-talk.gif
needs rounded corners

2023-06-08 13:42 UTC, szaimen commented on developer_manual/images/avatar-talk.gif
reported in https://github.com/nextcloud/server/issues/38712

2023-06-08 13:48 UTC, szaimen commented on developer_manual/images/dropdown-find-as-you-type.gif
Reported to https://github.com/nextcloud/server/issues/38713

2023-06-08 13:52 UTC, szaimen commented on developer_manual/images/skeleton-screen-talk.png
Reported to https://github.com/nextcloud/spreed/issues/9720

2023-06-08 13:55 UTC, szaimen commented on developer_manual/images/meter-settings.png
reported to https://github.com/nextcloud/nextcloud-vue/issues/4199

2023-06-08 14:02 UTC, szaimen commented on developer_manual/images/deck-card-modal.png
fixed

2023-06-08 15:32 UTC, szaimen commented on developer_manual/images/talk-counter-bubble.png
fixed

2023-06-08 15:33 UTC, szaimen commented on developer_manual/images/talk-counter-bubble.png
https://github.com/nextcloud/nextcloud-vue/issues/4200

2023-06-08 15:36 UTC, szaimen commented
@jancborchardt @nimishavijay can you please approve? Should everything be fixed or reported now :)

2023-06-09 09:01 UTC, szaimen commented
@nextcloud/designers can you please give me an approval? All should be fixed or reported now :)

2023-06-12 08:47 UTC, marcoambrosini approved these changes
🐘

2023-06-12 08:54 UTC, szaimen commented
Thanks Marco! :)

2023-06-12 08:54 UTC, merged