Admin docs: Add a section on AI features
nextcloud/documentation pull request #10774
Opened 2023-07-18 10:59 UTC by marcelklehr

### ☑️ Resolves

* Nothing :(

### 🖼️ Screenshots

![image](https://github.com/nextcloud/documentation/assets/986878/3d8f557c-4783-437e-952f-b79c697671b1)

2023-07-18 10:59 UTC, marcelklehr commented
Anything else I should add?

2023-07-18 11:37 UTC, bigcat88 approved these changes
looks really cool!

2023-07-18 12:18 UTC, DaphneMuller commented
maybe use instead of "implementation" > "app name" and provide a URL to the app store

2023-07-18 12:18 UTC, DaphneMuller commented
i love the table, the explanation you made of the ethical AI rating, and the extra explanation of that there are multiple apps implementing the same feature. I can see you put a lot of work in it, thanks a lot

2023-07-18 12:53 UTC, DaphneMuller approved these changes

2023-07-18 12:54 UTC, julien-nc requested changes
:blue_heart: :+1:

2023-07-18 12:54 UTC, julien-nc commented on admin_manual/ai/index.rst
> +In downstream apps like the Text app, users can use the translation functionality regardless of which app implements it behind the scenes.
```suggestion
In downstream apps like the Text app, users can use the translation feature regardless of which app implements it behind the scenes.
```
Nitpicking, optional change :grin:

2023-07-18 12:54 UTC, julien-nc commented on admin_manual/ai/index.rst
> + * Is the software (both for inferencing and training) open source?
```suggestion
 * Is the software (both for inferencing and training) under a free and open source license?
```

2023-07-18 12:58 UTC, marcelklehr commented on admin_manual/ai/index.rst
> +   "Machine translation","translate","Green 🟢","✅","✅ - Opus models by University Helsinki","✅","✅"
Yes :)

2023-07-18 12:59 UTC, marcelklehr commented on admin_manual/ai/index.rst
> +In downstream apps like the Text app, users can use the translation functionality regardless of which app implements it behind the scenes.
:D

2023-07-21 13:12 UTC, merged

2023-07-21 13:12 UTC, marcelklehr commented
Do we backport this to stable27?

2023-07-24 08:31 UTC, DaphneMuller commented
> Do we backport this to stable27?

up to you to decide  💙

2023-07-24 09:14 UTC, marcelklehr commented
/backport to stable27