Update example_centos.rst for PHP8.2
nextcloud/documentation pull request #11191
Opened 2023-10-11 14:09 UTC by hellodarkness

### ☑️ Resolves

* Fix #9650 

### 🖼️ Screenshots

![centos](https://github.com/nextcloud/documentation/assets/111370255/42df51a4-652b-4378-bf8c-6113c37e137b)

2023-10-14 14:31 UTC, kesselb requested changes
Thanks :+1:

2023-10-14 14:31 UTC, kesselb commented on admin_manual/installation/example_centos.rst
>      dnf install -y php php-gd php-mbstring php-intl php-pecl-apcu\
```suggestion
    dnf install -y php php-cli php-gd php-mbstring php-intl php-pecl-apcu\
```

2023-10-14 14:31 UTC, kesselb commented on admin_manual/installation/example_centos.rst
> +    dnf install php-cli
```suggestion
```

2023-10-17 13:29 UTC, hellodarkness commented
> Thanks 👍

I'd originally kept php-cli separate as it's optional but fair point, your way is more concise!

2023-10-17 13:42 UTC, kesselb commented
> php-cli separate as it's optional

You cannot use occ without, and therefore it's not really optional ;)

2023-10-17 17:27 UTC, kesselb approved these changes

2023-10-17 17:27 UTC, merged

2023-10-17 17:41 UTC, kesselb commented
/backport to stable27