Document shared item feature for contacts
nextcloud/documentation pull request #11270
Opened 2023-11-07 07:57 UTC by GretaD

### ☑️ Resolves

* Fix https://github.com/nextcloud/contacts/pull/3670

### 🖼️ Screenshots

2023-11-07 13:55 UTC, ChristophWurst requested changes
Add a screenshot of the rendered page

2023-11-07 13:55 UTC, ChristophWurst commented on user_manual/groupware/contacts.rst
> +The contact app supports shared item starting from version 5.5.0. Media, calendar events, talk chat room between you and another contact or shared deck cards, will be shown on the contact details. Yo
* The user can't enable an app. Drop the note about enabled app.
* Use https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded to render when the feature was added.
* Add note that this only works for contacts in the *system address book*

2023-11-07 19:49 UTC, ChristophWurst reviewed
:sunglasses:

2023-11-07 19:49 UTC, ChristophWurst commented on user_manual/groupware/contacts.rst
> +.. figure:: ../images/shared-items.png
I meant a screenshot for the PR description but this is nice too :)

2023-11-08 09:25 UTC, ChristophWurst reviewed
:+1: Add a screenshot of the modified docs page to the PR then we can merge

2023-11-08 10:04 UTC, GretaD commented
> 👍 Add a screenshot of the modified docs page to the PR then we can merge

the way how you add images on github has changed. I couldnt find how to do it and assumed is a temporary issue.

![Screenshot from 2023-11-08 10-52-29](https://github.com/nextcloud/documentation/assets/12728974/d18693b0-00be-4a2c-beb8-a17e172704cf)

2023-11-08 11:53 UTC, ChristophWurst approved these changes
Very nice

2023-11-08 11:53 UTC, ChristophWurst commented
This is only to be merged when the feature PR is in, in case there is a delay

2023-11-09 19:37 UTC, hamza221 approved these changes

2023-11-10 09:45 UTC, merged