doc(files_versions): added API doc for file versions
nextcloud/documentation pull request #11642
Opened 2024-03-12 14:17 UTC by emoral435

### 🖼️ Screenshots
https://github.com/nextcloud/documentation/assets/110193237/9387da98-f615-409e-869e-d3c9f47a6d76

### Summary
With the upcoming release for stable29, files_versions is releasing a new API `version-author` that allows uses to get the version author of a file version. This documents that API, as well as documents the `version-label` API.

2024-03-12 16:40 UTC, susnux approved these changes

2024-03-12 16:53 UTC, artonge requested changes

2024-03-12 16:53 UTC, artonge commented on developer_manual/client_apis/WebDAV/basic.rst
> +|                               |                                                 | | ``Current version`` = The most recent version of the file.                         |
'Initial version' and 'Current version' is done in the front end, not sent by the server

2024-03-13 15:50 UTC, emoral435 commented
@artonge I changed the description of the API to be `The user-set label for a file.` and left the example section empty, in-line with the other example sections that can contain other user/file specific details. Let me know if you would want to provide a more concrete example for your API, though !

2024-03-13 15:58 UTC, artonge approved these changes

2024-03-13 16:17 UTC, merged