Add documentation for simple and advance search
nextcloud/documentation pull request #11863
Opened 2024-05-27 16:18 UTC by GretaD

### ☑️ Resolves

* Fix https://github.com/nextcloud/mail/pull/9599

### 🖼️ Screenshots

2024-06-20 10:41 UTC, kesselb commented on user_manual/groupware/mail.rst
> +.. figure:: ../images/mail_layout.png
```suggestion
.. figure:: images/mail_layout.png
```

2024-06-20 10:41 UTC, kesselb commented on user_manual/groupware/mail.rst
> +.. figure:: ../images/new-mail-account.png
```suggestion
.. figure:: images/new-mail-account.png
```

2024-06-20 12:36 UTC, ChristophWurst requested changes
Let's remove the screenshot because it will get outdated quicky and they contain sensitive information

2024-06-21 07:18 UTC, GretaD commented
> Let's remove the screenshot because it will get outdated quicky and they contain sensitive information

the whole should know that we have team calls.

2024-07-24 14:50 UTC, ChristophWurst commented on user_manual/groupware/mail.rst
> +.. figure:: ../images/mail_layout.png
The file is located at https://github.com/nextcloud/documentation/blob/e20930354174492c20c95dcb8ee621df3728e6a2/user_manual/groupware/images/mail_layout.png, not https://github.com/nextcloud/documentation/blob/e20930354174492c20c95dcb8ee621df3728e6a2/user_manual/images/mail_layout.png

2024-07-24 15:24 UTC, ChristophWurst requested changes

2024-07-24 15:24 UTC, ChristophWurst commented on user_manual/groupware/mail.rst
> +.. figure:: ../images/new-mail-account.png
please provide screenshots. this does not render.

2024-07-24 15:24 UTC, ChristophWurst commented on user_manual/groupware/mail.rst
> +.. figure:: ../images/new-mail-account.png
@GretaD ^

2024-07-24 15:32 UTC, ChristophWurst commented
yes?

2024-07-24 15:33 UTC, ChristophWurst commented
https://github.com/nextcloud/documentation/actions/runs/10079255937/job/27866159958?pr=11863

> Warning, treated as error:
> /home/runner/actions-runner/_work/documentation/documentation/user_manual/groupware/mail.rst:30:image file not > readable: images/new-mail-account.png
> make: *** [Makefile:65: html-lang-en] Error 2

2024-07-24 16:15 UTC, GretaD commented
> https://github.com/nextcloud/documentation/actions/runs/10079255937/job/27866159958?pr=11863
> 
> > Warning, treated as error:
> > /home/runner/actions-runner/_work/documentation/documentation/user_manual/groupware/mail.rst:30:image file not > readable: images/new-mail-account.png
> > make: *** [Makefile:65: html-lang-en] Error 2

sorry, i changed the files folder and forgot to change the path

2024-07-24 20:13 UTC, kesselb approved these changes
LGTM :+1:

2024-07-25 07:35 UTC, merged