Add documentation for contacts organization chart
nextcloud/documentation pull request #12259
Opened 2024-10-02 07:54 UTC by Brijeshthummar02

### ☑️ Resolves #12127

2024-10-28 10:08 UTC, Brijeshthummar02 commented
@susnux any update?

2024-10-28 10:29 UTC, susnux commented
I have no idea about the contacts chart, so waiting for a review of someone of the groupware team.
cc @hamza221 @SebastianKrupinski

2024-10-28 12:28 UTC, SebastianKrupinski approved these changes

2024-10-28 12:33 UTC, SebastianKrupinski commented
Hi @Brijeshthummar02,

Thanks for the pull request. Can I just get you to just squash all your commits in to one, please.

2024-10-28 12:46 UTC, Brijeshthummar02 commented
@SebastianKrupinski yeahh sure, so should it be done by you or me?

2024-10-28 12:54 UTC, SebastianKrupinski commented
> @SebastianKrupinski yeahh sure, so should it be done by you or me?

Needs to be done by you.

2024-10-30 11:23 UTC, hamza221 requested changes

2024-10-30 11:23 UTC, hamza221 commented on user_manual/groupware/contacts.rst
> +- The user must be part of the system address book.
all users are part of the system addressBook afaik

2024-10-30 11:23 UTC, hamza221 commented on user_manual/groupware/contacts.rst
> +3. Under the **Manager** field, search and select the manager from the system address book.
```suggestion
3. Under the **Line manager** field, search and select the manager from the system address book.
```

2024-10-30 11:23 UTC, hamza221 commented on user_manual/groupware/contacts.rst
> +The organization chart feature only works with users listed in the system address book. Ensure that all relevant users are added to the address book for this functionality to be effective.
Not necessarily, SAB contacts can't be edited and you'll have to set the manager in the accounts settings as an Admin,
You can set managers and create charts for contacts in other ABs from the contacts app

2024-10-30 11:24 UTC, hamza221 commented
And can you please add a screenshot

2024-10-30 11:25 UTC, Brijeshthummar02 commented
@hamza221 screenshot of what?

2024-10-30 11:28 UTC, hamza221 commented
> @hamza221 screenshot of what?

Of your changes

2026-05-06 09:13 UTC, skjnldsv commented
As there is no feedback since a while I will close this ticket. 
If you will decide to work on this feature again and if it hasn't been fixed or implemented already, feel free to re-open, solve the various conflicts and address the review comments :)

Thanks for the interest in Nextcloud and the effort put into this! 🙇

2026-05-06 09:13 UTC, closed without merging