Version detection
nextcloud/documentation pull request #12368
Opened 2024-11-15 01:09 UTC by sputnick-dev

In the previous command, the `|&` was not a typo but intentional. Was removed outside of github AFAIK.

The output of `php occ version` is on `STDERR`.

Anyway, now this is a POSIX way to detect version.

### ☑️ Resolves

* Fix #…

### 🖼️ Screenshots

2025-05-01 13:27 UTC, sputnick-dev commented
6 month later, still not merged?

2025-05-01 14:44 UTC, sputnick-dev commented
> > 6 month later, still not merged?
> 
> Looks like.
> 
> Have you seen my comment?

You don't provide sufficient information.

Better copy/paste the whole execution commands with the proper `cd`

2025-05-03 22:43 UTC, szaimen requested changes

2025-05-03 22:43 UTC, szaimen commented on developer_manual/digging_deeper/profiler.rst
> +   major_version=$(php occ version 2>&1 | awk -F'[. ]' '{print $2;exit}')
```suggestion
   major_version=$(sudo -E -u www-data php occ version 2>&1 | awk -F'[. ]' '{print $2;exit}')
```

2025-05-04 10:49 UTC, sputnick-dev reviewed
Done required changes

2025-05-05 08:25 UTC, szaimen approved these changes
Tested and seems to work

2025-05-05 08:30 UTC, merged