Fix get task by id method
nextcloud/documentation pull request #12371
Opened 2024-11-16 20:36 UTC by SystemKeeper

Refs:

https://github.com/nextcloud/server/blob/67a02fa611c8a88dc500cff2c93033bb3db436b7/core/Controller/TaskProcessingApiController.php#L162-L178

https://github.com/nextcloud/server/blob/67a02fa611c8a88dc500cff2c93033bb3db436b7/core/Controller/TextProcessingApiController.php#L140-L155

https://github.com/nextcloud/server/blob/67a02fa611c8a88dc500cff2c93033bb3db436b7/core/Controller/TextToImageApiController.php#L115-L132

2024-11-16 20:37 UTC, SystemKeeper commented
/backport to stable30

2024-11-16 20:37 UTC, SystemKeeper commented
/backport bc1c292b367f1a63a5afffedc8325031f81a1ab8 to stable29

2024-11-16 20:37 UTC, SystemKeeper commented
/backport bc1c292b367f1a63a5afffedc8325031f81a1ab8 to stable28

2024-11-16 20:39 UTC, SystemKeeper commented
Now that I look at it again, I think the note about ratelimit is also wrong here and only belongs to the schedule endpoint?

2024-11-18 07:58 UTC, marcelklehr commented
Yes, well spotted! The POST should be a GET, the ratelimit should be for the schedule endpoint. For TaskProcessing the status is a string nowadays, indeed. Initially it was an int.

2024-11-18 07:59 UTC, marcelklehr approved these changes

2025-03-30 13:50 UTC, marcelklehr requested changes

2025-03-30 13:50 UTC, marcelklehr commented on developer_manual/client_apis/OCS/ocs-taskprocessing-api.rst
> -.. TODO ON RELEASE: Update version number above on release
This should probably be kept, I think

2025-03-31 07:11 UTC, marcelklehr approved these changes

2025-03-31 07:14 UTC, SystemKeeper commented
That PR differs now from the original idea, let me take another look.

2025-03-31 14:54 UTC, closed without merging

2025-03-31 14:54 UTC, SystemKeeper commented
The part I wanted to update, was removed and linked to the OpenAPI docs in https://github.com/nextcloud/documentation/commit/50948b909f4d5944a9e094b161491e53a3a260dc. That's why the diff now looks weird. We can close this then, the OpenAPI docs should be fine.
Thanks for taking a look @rakekniven !