Update Windows solution and alternate connection address.
nextcloud/documentation pull request #1505
Opened 2019-06-20 18:03 UTC by kuipumu

Based on multiple error trying to connect to multiple Nextcloud 16 servers thought WebDav, the correct address to get access from File Explorer or CLI is \\domain.comSSL\DavWWWRoot\remote.php\dav\files\username or if a subdomain is present (has in the current manual example)  \\domain.comSSL\DavWWWRoot\subdomain\remote.php\dav\files\username. Also add another solution to WebDav connection problems based on the "WebClient" service from Windows not beign started.

A part of the problem it's described in this next Nextcloud forum topic: https://help.nextcloud.com/t/webdav-problems-in-windows-7-8-10

2019-06-21 08:33 UTC, skjnldsv commented
Wow, how weird is that!
https://superuser.com/questions/494203/how-to-access-webdav-using-windows-explorer-on-windows-7

2019-07-06 22:32 UTC, tflidd commented
Interesting. Is this working properly, meaning is the connection stable an fast? Currently in the forums, we rather recommend to use 3rd party software and it would be cool to have a native implementation that works well. And which windows versions are working with that solution (if it works for one environment, we can ask the community to help with other versions)?

2022-04-21 13:23 UTC, tflidd requested changes
I just tried on Windows 10,
I had to adjust the registry, then start the Service manually, after that it was working!

We should clear up the thing, if Nextcloud is used in a subfolder or not and we are ready to go.

Before I did the modifictions, it tried to call the resource `/login` from the webserver which failed with a 405 error. Might help others where the service is not started and/or registry not yet fixed.

edit: Tested with NC 22.2.6 & NC 24 RC1

2022-04-21 13:23 UTC, tflidd commented on user_manual/files/access_webdav.rst
> +  net use Z: \\example.com@ssl\DavWWWRoot\nextcloud\remote.php\dav\files\youruser /user:youruser
That is if nextcloud is installed in a subfolder. For other reasons, this is not the preferred way, but it should be clear that the nextcloud folder is only required in this case.

2024-11-13 18:19 UTC, susnux commented
This seems to be stale as there is no activity for over two years.
With Window 10 and 11 it seems to work fine just using `\\domain.com\subdir/remote.php/dav/files/admin`.

Please feel free to re-open if you want to work on it.

2024-11-13 18:19 UTC, closed without merging