Removal of the word "top"
nextcloud/documentation pull request #5103
Opened 2020-09-27 18:57 UTC by Valdnet

2020-09-27 20:37 UTC, AndyScherzinger requested changes
Reading the diff: the "top" seems right

2020-09-28 07:43 UTC, Valdnet commented
The disk usage space is not at the top of the personal page. 

![obraz](https://user-images.githubusercontent.com/47037905/94403418-b08c9b80-016d-11eb-9f47-5f373854da77.png)

Unless it's about the location on the menu, that is:

![obraz](https://user-images.githubusercontent.com/47037905/94403746-298bf300-016e-11eb-981d-334886fe3796.png)

or where the user menu is located:

![obraz](https://user-images.githubusercontent.com/47037905/94403820-458f9480-016e-11eb-9f86-61b9cc85c3ee.png)

I also removed "the". My oversight.

If I'm wrong, correct me 😉.

2020-09-28 07:46 UTC, AndyScherzinger commented on user_manual/files/quota.rst
> +the of your Personal page to see what your quota is, and how much you have
@Valdnet see here, the sentence is due to your change:

```
Look at the of your Personal page to see what your quota is, and how much you have used.
```

Which is not a proper sentence.

Did you forget to push your second change maybe?

2020-09-28 07:47 UTC, AndyScherzinger requested changes

2020-09-28 07:47 UTC, AndyScherzinger commented on user_manual/files/quota.rst
> +of your Personal page to see what your quota is, and how much you have used.
@Valdnet I'd say you would at least have to also remove "of" else the sentence is incorrect/incomplete, no?

2020-09-28 08:04 UTC, Valdnet commented
You're right. One more change 😉.

2020-09-28 09:56 UTC, AndyScherzinger approved these changes

2020-09-28 09:57 UTC, merged