Add support to OpenBSD
nextcloud/documentation pull request #6218
Opened 2021-02-19 17:31 UTC by gonzalo-

@kesselb  I hope this time everything is good :D

2021-02-19 17:37 UTC, kesselb commented
Thanks @gonzalo- :+1: 

Linter and DCO looks good.

2021-03-15 12:17 UTC, gonzalo- commented
No love for this? :D

2021-03-15 21:08 UTC, kesselb requested changes

2021-03-15 21:08 UTC, kesselb commented on admin_manual/installation/example_openbsd.rst
> +Nextcloud does not have official OpenBSD or other BSDs support
![image](https://user-images.githubusercontent.com/3902676/111221465-cfc39c00-85da-11eb-9d01-77dd14218e7a.png)

> Nextcloud does not have official OpenBSD or other BSDs support

Is now a navigation item. Can you use the box again?

2021-03-15 21:12 UTC, kesselb commented on admin_manual/installation/example_openbsd.rst
> +Nextcloud does not have official OpenBSD or other BSDs support
```
.. _openbsd_installation_label:

Example installation on OpenBSD
===============================

.. warning::

    Nextcloud does not have official OpenBSD or other BSDs support

In this install tutorial we will be deploying Nextcloud on a minimal OpenBSD with our own httpd(8), PHP, PostgreSQL and redis (for -stable or -current are the same steps).
```

![image](https://user-images.githubusercontent.com/3902676/111221917-6abc7600-85db-11eb-8afe-a8298bde3d14.png)

2021-03-16 10:27 UTC, kesselb approved these changes

2021-03-16 10:27 UTC, kesselb commented
@gonzalo- mind to fix the DCO?

2021-03-16 11:26 UTC, gonzalo- commented
Uff I did it from github website can I fix it from here? it is really important?

2021-03-16 12:50 UTC, kesselb commented
`git commit --amend --no-edit --signoff`
`git push --force-with-lease origin master`

2021-03-16 19:47 UTC, gonzalo- commented
Done!

2021-03-16 19:54 UTC, merged

2021-03-16 19:54 UTC, kesselb commented
Thanks @gonzalo- :+1: