MariaDB 10.6 is not supported
nextcloud/documentation pull request #6972
Opened 2021-07-15 20:48 UTC by kesselb

2021-07-16 07:48 UTC, skjnldsv approved these changes

2021-07-20 19:40 UTC, rugk requested changes

2021-07-20 19:40 UTC, rugk commented on admin_manual/installation/system_requirements.rst
> +| Database         | - **MySQL 8.0+ or MariaDB 10.2/10.3/10.4/10.5 ** (recommended)        |
```suggestion
| Database         | - **MySQL 8.0+ or MariaDB 10.2/10.3/10.4/10.5** (recommended)        |
```

You have a syntax error here…

2021-07-20 20:22 UTC, kesselb commented on admin_manual/installation/system_requirements.rst
> +| Database         | - **MySQL 8.0+ or MariaDB 10.2/10.3/10.4/10.5 ** (recommended)        |
Thanks :+1:

2021-07-20 20:40 UTC, merged

2021-07-20 20:40 UTC, kesselb commented
/backport to stable22

2021-07-20 20:40 UTC, kesselb commented
/backport to stable20

2021-07-21 08:29 UTC, My1 commented
I went ahead and did the manual backport, as I didnt see any other PR for it.