Use consistent data size units
nextcloud/documentation pull request #8006
Opened 2022-02-07 01:44 UTC by carlcsaposs

Signed-off-by: Carl Csaposs <carl@csaposs.com>

2022-02-07 01:51 UTC, carlcsaposs commented
Should binary byte units be specified according to [ISO/IEC 80000-13](https://en.wikipedia.org/wiki/ISO/IEC_80000#Part_13:_Information_science_and_technology) (e.g. kibibyte, KiB)?

PHP uses "kilobyte" to represent 1024 bytes: https://www.php.net/manual/en/faq.using.php#faq.using.shorthandbytes
Nextcloud's front-end appears to do the same

2022-02-07 02:01 UTC, carlcsaposs commented on developer_manual/client_apis/WebDAV/search.rst
> +Get all png and jpg files over 10 MB.
This example uses 10 MB = 10000000 bytes (see line 207)

2022-02-22 13:20 UTC, nickvergessen commented on admin_manual/configuration_files/big_file_upload_configuration.rst
>  ===========================
```suggestion
============================
```

2022-02-22 13:26 UTC, nickvergessen requested changes

2022-02-22 13:26 UTC, nickvergessen commented on admin_manual/configuration_files/big_file_upload_configuration.rst
>  ===========================
```rst
============================
Uploading big files > 512 MB
============================
```

Need to adjust the count of `=` as well

2022-02-22 13:26 UTC, nickvergessen commented on admin_manual/configuration_files/big_file_upload_configuration.rst
> +Default is 10485760 (10 MB).
MiB is actually correct here.
1MB = 1.000 KB
1 MiB = 1.024 KiB

2022-02-22 13:26 UTC, nickvergessen commented on admin_manual/configuration_server/config_sample_php_parameters.rst
> +The memory in KB to be used by the algorithm for computing a hash. The value
also incorrect

2022-02-22 13:26 UTC, nickvergessen commented on admin_manual/installation/nginx.rst
> +Upload of files greater than 10 MB fails
also wrong

2022-02-22 13:26 UTC, nickvergessen commented on admin_manual/installation/nginx.rst
> +it may be not possible to upload files greater than 10 MB using the webpage
also wrong

2022-02-24 17:34 UTC, carlcsaposs commented
> Should binary byte units be specified according to [ISO/IEC 80000-13](https://en.wikipedia.org/wiki/ISO/IEC_80000#Part_13:_Information_science_and_technology) (e.g. kibibyte, KiB)?
> 
> PHP uses "kilobyte" to represent 1024 bytes: https://www.php.net/manual/en/faq.using.php#faq.using.shorthandbytes Nextcloud's front-end appears to do the same

@nickvergessen Here's a branch with ISO 80000-13 units: https://github.com/nextcloud/documentation/compare/master...carlcsaposs:units-iso

Should the documentation follow the ISO 80000-13 standard or the [Nextcloud front-end](https://github.com/nextcloud/server/blob/6da8a6d62adde9b1ed011a7a18d43984cf5a27a8/lib/private/legacy/OC_Helper.php#L64) and PHP standard?

Please let me know if you'd like me to push the changes on the `carlcsaposs:units-iso` branch to this PR.

---

Also, it appears that the comments in Nextcloud's source code use inconsistent units (see [this example](https://github.com/nextcloud/server/blob/6da8a6d62adde9b1ed011a7a18d43984cf5a27a8/lib/private/legacy/OC_Files.php#L57) and [this example](https://github.com/nextcloud/server/blob/6da8a6d62adde9b1ed011a7a18d43984cf5a27a8/apps/files_external/3rdparty/icewind/smb/src/Native/NativeReadStream.php#L16)).

I'd be happy to submit PRs to update the units across Nextcloud's repositories--please let me know if that would be useful.

2022-04-21 10:09 UTC, tflidd commented
It's better to call things what they are. Advantage of the Si-units is that you have MiB and MB to make a difference.

Question now would be, if php consiers 1M to be 1 MiB, and now you want to set a quota, do we show that you need to select a value in MiB, or do we ask a value in MB and then do the internal conversion to MiB to apply the limit via php?
And we have the clients as well.

There was a long discussion before the fork about the use of SI units: https://github.com/owncloud/core/issues/13386

2022-04-30 16:43 UTC, carlcsaposs commented
@tflidd I appreciate you sharing the context of the owncloud issue--I didn't think to search owncloud repositories.  Thank you!

2022-11-14 07:47 UTC, closed without merging