Clarification on permisions for the Redis socket
nextcloud/documentation pull request #8189
Opened 2022-04-15 06:24 UTC by FalkenStein42

After running into the problem myself and searching online for a solution i think a clarification on how to ensure proper permissions on the redis socket would be helpful to novice administrators

 Signed-off-by: Sergio Solé Rodríguez <sergio@sergiosole.dev>

2022-04-21 09:00 UTC, tflidd reviewed
You need to restart `redis` and `redis-server`?

2022-04-21 17:23 UTC, FalkenStein42 commented
I am sure redis-server needs to be restarted in order to regenerate the redis socket file, whether you have to restart the client as well i am unsure as i restarted everything once i applied the configuration

2022-04-22 05:26 UTC, tflidd commented
In some oler tutorial that included redis, it just restarts `redis-server` (https://bayton.org/docs/nextcloud/installing-nextcloud-on-ubuntu-16-04-lts-with-redis-apcu-ssl-apache/). However, it says that you need to add redis to the services to be started at startup whereas the current Nextcloud documentation says this is automatically done. Not sure if you can easily verify this? I currently don't have a native Linux setup at hand to test it...

2022-05-02 09:32 UTC, tflidd requested changes

2022-05-02 09:32 UTC, tflidd commented on admin_manual/configuration_server/caching_configuration.rst
> + systemctl restart redis
I just installed `redis-server` on ubuntu. In this case, you have `redis-server` as service. `redis` in this case is just an alias and this way you would restart redis twice:
![image](https://user-images.githubusercontent.com/8111200/166214070-df1f567c-5926-4f3f-9cc4-9142684f10ed.png)

Let's just keep the redis-server.

2022-10-11 07:09 UTC, FalkenStein42 commented
I have come acros a similar tutorial that just said 'restart redis' or something like that but didnt give a specific answer either. I could set up a quick vm to test it this week and maybe make a more comprehensive exlplanation of other parts.
Id prefer if someone familiar with redis / php cache in general help me with configuration as i am fairly new to it.
I could just test only wich components need to be restarted though.

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------
On Friday, April 22nd, 2022 at 07:26, tflidd ***@***.***> wrote:

> In some oler tutorial that included redis, it just restarts redis-server (https://bayton.org/docs/nextcloud/installing-nextcloud-on-ubuntu-16-04-lts-with-redis-apcu-ssl-apache/). However, it says that you need to add redis to the services to be started at startup whereas the current Nextcloud documentation says this is automatically done. Not sure if you can easily verify this? I currently don't have a native Linux setup at hand to test it...
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/nextcloud/documentation/pull/8189#issuecomment-1106024081), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/ALMIJY47WJE7RQYIYNJWAWLVGIZ7JANCNFSM5TPWODLA).
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-12-29 14:13 UTC, kesselb commented on admin_manual/configuration_server/caching_configuration.rst
> + systemctl restart redis
```suggestion
```

2022-12-29 14:15 UTC, kesselb approved these changes
Thanks :+1:

2022-12-29 14:19 UTC, merged

2023-01-30 10:55 UTC, tflidd commented
/backport to stable24