Update adding CrowdSec
nextcloud/documentation pull request #9154
Opened 2022-09-09 03:13 UTC by slimshizn

Signed-off-by: SS <23506499+slimshizn@users.noreply.github.com>

2022-09-11 19:39 UTC, kesselb commented
Hey :wave: 

Thanks for your pull request. I'm not a fan of duplicating the installation instructions of another software here. At worst it's outdated in a few weeks. 

I didn't know about CrowdSec until your pull request. However from your pull request I could not figure out what this is about. I would like for our documentation a short introduction about CrowdSec (what is it good for) and a link to their documentation how to configure it with Nextcloud.

2022-09-11 19:57 UTC, slimshizn commented
Understood! I can do that for sure. Thanks for answering the PR so it doesn't sit forever. I'll probably get to that this week sometime.

2022-09-28 15:53 UTC, slimshizn reviewed
How's this?

2022-10-01 19:24 UTC, kesselb commented
> How's this?

Thank you! Looks good to me. 

I'm still undecided about the step by step guide. How to install the component belongs to their documentation. 

Let's see what Andy thinks about adding CrowdSec.

2022-10-02 15:54 UTC, AndyScherzinger commented
I'll check together with @nickvergessen but am currently afk

2022-10-17 21:56 UTC, tflidd commented
I think the tipps should be for secure configuration for services that are needed to run Nextcloud (e.g. webserver, database) and that might not be well adjusted in default settings. And it should be rather general, not just for some container solutions that require a special setup....

Beyond that, there are many solutions and it's a lot of work to keep such tutorials updated for different distributions. I'd perhaps mention different possible solutions (intrusion detection, ip blocking, ....) and then link to existing open source solutions and their tutorials.

2022-10-18 16:19 UTC, slimshizn commented
Well this is purely for hardening your server, hence "harden_server.rst". I purely respect any input, but I think this is something that is 'aftermarket' and was put in a 'aftermarket' area. Just my thoughts.

2022-10-20 07:15 UTC, nickvergessen requested changes

2022-10-20 07:15 UTC, nickvergessen commented on admin_manual/installation/harden_server.rst
> +    Compile CrowdSec using the usual make command
This is a pure copy of https://docs.crowdsec.net/docs/getting_started/install_crowdsec (which might even violate author rights).

So I would suggest to simply replace it with something like:

> Follow the install instructions presented at https://docs.crowdsec.net/docs/getting_started/install_crowdsec

And the part in our documentation should basically only focus on the configuration, like installing the nextcloud collection from https://hub.crowdsec.net/author/crowdsecurity/collections/nextcloud etc.

2022-10-20 07:15 UTC, nickvergessen commented on admin_manual/installation/harden_server.rst
> +``hhttps://docs.ibracorp.io/crowdsec/crowdsec/docker-compose``
(Type here in the URL)

2022-10-20 07:15 UTC, nickvergessen commented on admin_manual/installation/harden_server.rst
> +Docker CrowdSec Install
Similar story as above also here. We should not copy the CrowdSec install docs but refer to them instead and focus on the configuration of the nextcloud collection

2022-10-20 07:22 UTC, nickvergessen commented on admin_manual/installation/harden_server.rst
> +    Compile CrowdSec using the usual make command
But also there don't copy the manual, if it's useful refer to the site, if it's a single line to execute good enough.

2026-04-23 09:21 UTC, skjnldsv commented
As there is no feedback since a while I will close this ticket. If this is still something you wish, please make sure to rebase to the latest master commit. After that, feel free to reopen.

2026-04-23 09:21 UTC, closed without merging