Add documentation for using SSE-C on S3 primary storage
nextcloud/documentation pull request #9414
Opened 2022-11-22 17:21 UTC by juliushaertl

Signed-off-by: Julius Härtl <jus@bitgrid.net>

2023-01-25 15:26 UTC, artonge requested changes

2023-01-25 15:26 UTC, artonge commented on admin_manual/configuration_files/primary_storage.rst
> +This means Nextcloud can encrypt files such storage, using a client provided key, the moment they are uploaded. The decryption key is provided by the client. We are using the `SSE-C provided by AWS <
I am not sure about that one.

- The files are encrypted on the bucket side, but it is not clear in `the moment they are uploaded.`
- Not sure about `a client provided key` and ` decryption key is provided by the client`. It seems that we are talking about two keys. But there is only one. Right ?
- This paragraph might go too much in the implementation details, and i don't think that an admin care about that

```suggestion
The encryption and decryption appens on the S3 bucket side with a key provided by the Nextcloud server.
```

2023-01-25 15:26 UTC, artonge commented on admin_manual/configuration_files/primary_storage.rst
> +Nextcloud added support for server side encryption (also known as SSE-C) with AWS.
```suggestion
Nextcloud supports server side encryption, also known as `SSE-C <http://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html>`, with compatible S3 bucket providers.
```

2023-01-25 15:26 UTC, artonge commented on admin_manual/configuration_files/primary_storage.rst
> +The key can be specified with the :code:`sse_c_key` parameter which needs to be provided as a base64 encoded string with a maximum length of 32 bytes, if it does not meet the requirements. The key ca
What does `if it does not meet the requirements` means in the sentence ?

```suggestion
You can specify the key by setting the :code:`sse_c_key` parameter in you config.php file. It needs to be provided as a base64 encoded string with a maximum length of 32 bytes.
The key can be generated using the the following command:
```

2023-01-31 08:34 UTC, juliushaertl commented
Thanks @artonge Good catches, adjusted that accordingly.

2023-01-31 10:32 UTC, artonge approved these changes
:ok_hand:

2023-01-31 10:34 UTC, merged